
import type { Metadata } from "next";
import "./globals.css";
import { StoreProvider } from "../store/StoreProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <div className="bg-slate-400  w-full ">
            {children}
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
