import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body>
        <div className="bg-slate-200 w-full px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64">
          <Navbar/>
        </div>
        <div className="bg-slate-400 px-4 w-full md:px-8 lg:px-10 xl:px-10 2xl:px-20  ">
          {children}
        </div>

      </body>
    </html>
    </ClerkProvider>
  );
}
