import type { Metadata } from "next";
import "./globals.css";
import { StoreProvider } from "../store/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <div className="bg-slate-400 w-full">
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
